import Validator from '../../../../helpers/Validator';

export default function editMemberInputsAttributes({
  firstName,
  lastName,
  email,
  skype,
  mobilePhone,
  address,
  sex,
  startDate,
  birthDate,
  direction,
  education,
  universityAverageScore,
  mathScore,
}) {
  return [
    {
      type: 'text',
      name: 'firstName',
      description: 'First Name',
      value: firstName,
      byCharValidator: Validator.text,
    },
    {
      type: 'text',
      name: 'lastName',
      description: 'Last Name',
      value: lastName,
      byCharValidator: Validator.text,
    },
    {
      type: 'text',
      name: 'email',
      description: 'Email',
      value: email,
      validator: Validator.email,
    },
    {
      type: 'text',
      name: 'skype',
      description: 'Skype',
      value: skype,
      byCharValidator: Validator.userName,
    },
    {
      type: 'text',
      name: 'mobilePhone',
      description: 'Mobile phone',
      value: mobilePhone,
      byCharValidator: Validator.mobilePhoneByChar,
      validator: Validator.mobilePhone,
    },
    {
      type: 'text',
      name: 'address',
      description: 'Address',
      value: address,
      byCharValidator: Validator.alphanumeric,
    },
    {
      type: 'radio',
      name: 'sex',
      description: 'Sex',
      value: sex,
      valueOptions: ['Male', 'Female'],
    },
    {
      type: 'text',
      name: 'startDate',
      description: 'Start date',
      value: startDate && Validator.fromDateToMask(startDate, 'dd-MM-yyyy'),
      mask: '99-99-9999',
      maskType: 'invisible',
      byCharValidator: (input) => Validator.dateByChar(input, ['dd-MM-yyyy']),
      validator: (input) => Validator.dateTime(input, ['dd-MM-yyyy']),
      validationMessage: Validator.dateTimeMessage,
    },
    {
      type: 'text',
      name: 'birthDate',
      description: 'Birth date',
      value: birthDate && Validator.fromDateToMask(birthDate, 'dd-MM-yyyy'),
      mask: '99-99-9999',
      maskType: 'invisible',
      byCharValidator: (input) => Validator.dateByChar(input, ['dd-MM-yyyy']),
      validator: (input) => Validator.dateTime(input, ['dd-MM-yyyy']),
      validationMessage: Validator.dateTimeMessage,
    },
    {
      type: 'select',
      name: 'direction',
      description: 'Direction',
      value: direction,
      valueOptions: ['Java', 'Salesforce', '.Net', 'Frontent'], //TODO Replace with request
    },
    {
      type: 'text',
      name: 'education',
      description: 'Education',
      value: education,
      byCharValidator: Validator.alphanumeric,
    },
    {
      type: 'text',
      name: 'universityAverageScore',
      description: 'University average score',
      value: universityAverageScore,
      byCharValidator: Validator.numeric,
      validator: (input) => Validator.float(input, 5, 10),
    },
    {
      type: 'text',
      name: 'mathScore',
      description: 'CT math score',
      value: mathScore,
      byCharValidator: Validator.numeric,
      validator: (input) => Validator.number(input, 20, 100),
    },
  ];
}
