export const SET_MEMBERS = 'SET_MEMBERS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const EDIT_MEMBER = 'EDIT_MEMBER';

export const ASSIGN_TASK = 'ASSIGN_TASK';
export const UNASSIGN_TASK = 'UNASSIGN_TASK';
export const SET_ASSIGNED_TO_TASK = 'SET_ASSIGNED_TO_TASK';
